### ISSUE TITLE
How are the bindings generated for each DLL?

### ISSUE THREAD

**Issue by r-lyeh** [Planimeter/lgameframework#10]
Hello @andrewmcwatters,

Hope you guys are doing well :o) Sorry if the question is a lil bit off-topic for this repo, but I have always wondered what kind of binding generator you guys had to run in order to generate the headers for each DLL. I always assumed you performed some kind of `gcc -E` on the official headers, then grep/replaced most unneeded lines. Is that process/dark magick recipe fully automatic, documented or exposed somewhere? ... cos I'd love me to have some kind of similar fully-automatic binding generators for my new pet project :o)

Have much fun & keep up the good work!,
- r-lyeh

**Comment by andrewmcwatters** [comment]
@r-lyeh Great question! Yes, we did in fact, do just that. Our automated process is based on some commentary by [Jonathan Leffler](https://stackoverflow.com/users/15168/jonathan-leffler) and documented at https://github.com/Planimeter/lffiutils.

Please ignore the license. It was automatically assigned an MIT permissive license, but it is really unlicensed code.

Instead, we recommend using `gcc -E` as you had mentioned, and implementing your own strategy to strip lines before passing the post-processed headers to LuaJIT's FFI module.

There's some modest work that can be done there that uses an open strategy mentioned in the LuaJIT documentation itself, and does not violate implicit copyrights that belong to Jonathan.

Please let me know if I can assist any further!

**Comment by r-lyeh** [comment]
thanks andrew! that's more or less what i was thinking but the complexity of the system headers problem pulled me off for real. scary! :D
however, got inspired and produced a smaller batch file that does the work for my limited use case at the moment :D
ty!

genffi.bat:
```bat
@echo off
if "%2"=="" ( echo genffi \some\folder file*.h;masks*.hh && exit /b )

set "tmp=%~dp0\x.$$"
pushd .
cd /d "%~dp1"
call :treeProcess %1 %2
popd
exit /b

:treeProcess
rem Process files: type contents, then remove includes, then run preprocessor without #lines, then remove blank lines
(for %%i in (*%2) do @(type %CD%\%%i | find /V "#include") > %tmp% && cl /Tc%tmp% -EP /nologo 2>nul ) | findstr /V "^$" & (del %tmp%  2>nul)

rem Iterate subfolders
for /D %%d in (*) do (
    cd %%d
    call :treeProcess %1 %2
    cd ..
)
exit /b
```

**Comment by andrewmcwatters** [comment]
@r-lyeh Kudos to you for doing this in batch, it's much harder than shell.

**Comment by r-lyeh** [comment]
ha np! my next revision is even simpler, and works better. dropping it here for the records.
`stubs\` folder here contains a full (empty) set of C/windows files (stdlib,h, math.h, windows.h, etc), as they're empty compiler will skip them quickly. for the rare cases where a definition is needed (ie, FILE* in stdio.h for example), then the stub header provides the minimal content.

```batch
cl /nologo -D__forceinline= my_api_header.h -EP -Istubs\ %* |^
findstr /R /C:"[^ ]" |^
find /V "static " |^
find /V "__pragma(" |^
find /V "#pragma once" |^
find /V "#pragma warning" |^
find /V "#pragma comment" |^
find /V "#pragma region" |^
find /V "#pragma endregion" >> api_for_luaffi.h
```
